# Generated by Django 5.0.6 on 2024-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('open', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Headersocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/headersocial/')),
                ('url', models.URLField()),
                ('platform', models.CharField(max_length=50)),
            ],
        ),
    ]
