# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0006_rename_from_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/testimonial/')),
                ('message', models.TextField(max_length=255)),
                ('patient_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
    ]
