# Generated by Django 5.0.6 on 2024-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/doctors/'),
        ),
    ]
