# Generated by Django 5.0.6 on 2024-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0008_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
