# Generated by Django 5.0.6 on 2024-06-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0009_doctor_facebook_url_doctor_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizederp',
            name='number',
            field=models.IntegerField(max_length=7),
        ),
    ]
