# Generated by Django 5.0.6 on 2024-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0010_alter_customizederp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizederp',
            name='number',
            field=models.IntegerField(),
        ),
    ]
