# Generated by Django 5.0.6 on 2024-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0011_alter_customizederp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
