# Generated by Django 5.0.6 on 2024-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0012_header_facebook_url_header_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='youtube',
            new_name='youtube_url',
        ),
    ]
