# Generated by Django 5.0.6 on 2024-06-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0015_about_about_content_remove_features_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/products/')),
            ],
        ),
    ]
