# Generated by Django 5.0.6 on 2024-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0017_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedERPTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/featuresbackground/')),
            ],
        ),
        migrations.DeleteModel(
            name='Headersocial',
        ),
    ]
