# Generated by Django 5.0.6 on 2024-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0018_customizederptitle_productbackgroundimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/featuresbackground/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/servicesbackground/')),
            ],
        ),
        migrations.AlterField(
            model_name='productbackgroundimage',
            name='image',
            field=models.ImageField(upload_to='images/productsbackground/'),
        ),
    ]
