# Generated by Django 5.0.6 on 2024-06-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneros', '0019_featuresbackgroundimage_servicesbackgroundimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAndLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/warehouseandlogistic/')),
            ],
        ),
    ]
